### ISSUE TITLE
minor issue

### ISSUE THREAD

**Issue by ghost** [baldengineers/easytf2_mapper#3]
your cap vmf has incredibly high z values (scientific notation levels, it should just be 64).

in addition to that, there arent any of the logic entities to go along with it.

**Comment by jonyTF** [comment]
Oh yeah lol. Just don't pay attention to that. I'll make a new cap point,
that other one was just a test.
Also, WTF you were up at 1:09AM working!?!?

**Comment by ghost** [comment]
false alarm
