### ISSUE TITLE
issue with respawn visualizers

### ISSUE THREAD

**Issue by ghost** [baldengineers/easytf2_mapper#5]
- 1. its not too important
- 2. its generating its own entity_num as its associated respawn room. to fix this we can make it so it detects if the entity_num of the parent of a visualizer is inside a respawn visualizer and change it accordingly, similar to what ive done with door triggers.

**Comment by jonyTF** [comment]
All right, I'll czech it out.

**Comment by ghost** [comment]
its done and fixed i think, you have to fix it in in the vmf prefab/hammer, not in the code.
